apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamguard-ml-deployment
  namespace: default
  labels:
    app: streamguard-ml
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamguard-ml
  template:
    metadata:
      labels:
        app: streamguard-ml
        version: v1
    spec:
      containers:
      - name: streamguard-ml
        image: streamguard-ml:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: FLASK_ENV
          value: "production"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: FLASK_APP
          value: "app.py"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
        - name: data-storage
          mountPath: /app/data
        - name: logs-storage
          mountPath: /app/logs
        - name: training-data
          mountPath: /app/train_transaction.csv
          subPath: train_transaction.csv
          readOnly: true
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: streamguard-models-pvc
      - name: data-storage
        persistentVolumeClaim:
          claimName: streamguard-data-pvc
      - name: logs-storage
        persistentVolumeClaim:
          claimName: streamguard-logs-pvc
      - name: training-data
        configMap:
          name: streamguard-training-data
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streamguard-models-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streamguard-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streamguard-logs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
